services:
  order-mngt-api:
    container_name: order-mngt-api
    hostname: order-mngt-api
    image: order-mngt-api
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3002:3002
    environment:
      - MAGENTO_URL=http://magento:8080
      - ELASTIC_APM_ENABLED=true
      - ELASTIC_APM_SERVICE_NAME=order-mngt-api
      - ELASTIC_APM_SERVER_URL=http://apm:8200
      - ELASTIC_APM_ENVIRONMENT=development
    depends_on:
      - magento
      - apm
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3002 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
    labels:
      - co.elastic.logs/enabled=true
      - co.elastic.logs/json.keys_under_root=true
      - co.elastic.logs/json.message_key=message
      - co.elastic.logs/json.overwrite_keys=true
      - co.elastic.metrics/enabled=false
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    command: "sh -c '/entrypoint.sh && npm run start:dev'"
